vars:
  zabbix_agent_Server: 10.10.0.50
  zabbix_agent_Server_Active: 10.10.0.50
  zabbix_agent_HostnameItem: system.hostname
  zabbix_agent_HostMetadataItem: system.uname
  zabbix_agent_AllowKey: system.run[*]


